### ISSUE TITLE
有空看看支付啥错误呗。

### ISSUE THREAD

**Issue by xch0911** [iam-tpc/chat-admin-web-test#1]
A神的版本好像覆盖错了。我现在只能在这个版本下继续了

**Comment by iam-tpc** [comment]
> A神的版本好像覆盖错了。我现在只能在这个版本下继续了

哈哈，我没得可以配置的支付信息，弄着玩的

**Comment by xch0911** [comment]
我搞定了。需要插入数据库一条数据。
